# Generated by Django 4.2.7 on 2023-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('weight', models.IntegerField(null=True, verbose_name='Вес')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Кот',
            },
        ),
    ]
