# Generated by Django 4.2.7 on 2023-11-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_roomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomUser',
        ),
    ]
